tally_mapping_state = {
    "Jammu & Kashmir": { "statename": "01 Jammu & Kashmir", "id": 1 },
    "Himachal Pradesh": { "statename": "02 Himachal Pradesh", "id": 2 },
    "Punjab": { "statename": "03 Punjab", "id": 3 },
    "Chandigarh": { "statename": "04 Chandigarh", "id": 4 },
    "Uttarakhand": { "statename": "05 Uttarakhand", "id": 5 },
    "Haryana": { "statename": "06 Haryana", "id": 6 },
    "Delhi": { "statename": "07 Delhi", "id": 7 },
    "Rajasthan": { "statename": "08 Rajasthan", "id": 8 },
    "Uttar Pradesh": { "statename": "09 Uttar Pradesh", "id": 9 },
    "Bihar": { "statename": "10 Bihar", "id": 10 },
    "Sikkim": { "statename": "11 Sikkim", "id": 11 },
    "Arunachal Pradesh": { "statename": "12 Arunachal Pradesh", "id": 12 },
    "Nagaland": { "statename": "13 Nagaland", "id": 13 },
    "Manipur": { "statename": "14 Manipur", "id": 14 },
    "Mizoram": { "statename": "15 Mizoram", "id": 15 },
    "Tripura": { "statename": "16 Tripura", "id": 16 },
    "Meghalaya": { "statename": "17 Meghalaya", "id": 17 },
    "Assam": { "statename": "18 Assam", "id": 18 },
    "West Bengal": { "statename": "19 West Bengal", "id": 19 },
    "Jharkhand": { "statename": "20 Jharkhand", "id": 20 },
    "Odisha": { "statename": "21 Odisha", "id": 21 },
    "Chhattisgarh": { "statename": "22 Chhattisgarh", "id": 22 },
    "Madhya Pradesh": { "statename": "23 Madhya Pradesh", "id": 23 },
    "Gujarat": { "statename": "24 Gujarat", "id": 24 },
    "Daman & Diu": { "statename": "25 Daman & Diu", "id": 25 },
    "Dadra & Nagar Haveli": { "statename": "26 Dadra & Nagar Haveli", "id": 26 },
    "Maharashtra": { "statename": "27 Maharashtra", "id": 27 },
    "Andra Pradesh (Old)": { "statename": "28 Andhra Pradesh (Old)", "id": 28 },
    "Karnataka": { "statename": "29 Karnataka", "id": 29 },
    "Goa": { "statename": "30 Goa", "id": 30 },
    "Lakshadweep": { "statename": "31 Lakshadweep", "id": 31 },
    "Kerala": { "statename": "32 Kerala", "id": 32 },
    "Tamil Nadu": { "statename": "33 Tamil Nadu", "id": 33 },
    "Puducherry": { "statename": "34 Puducherry", "id": 34 },
    "Andaman & Nicobar Islands": { "statename": "35 Andaman & Nicobar Islands", "id": 35 },
    "Telangana": { "statename": "36 Telangana", "id": 36 },
    "Andhra Pradesh": { "statename": "37 Andhra Pradesh (New)", "id": 37 },
    "Ladakh": { "statename": "38 Ladakh", "id": 38 }    
}

measurement = {
    'bou': 1,
    'bgs': 2,
    'bal': 3,
    'box': 4,
    'btl': 5,
    'bkl': 6,
    'bun': 7,
    'bdl': 8,
    'can': 9,
    'crt': 10,
    'ctn': 11,
    'cms': 12,
    'ccm': 13,
    'cbm': 14,
    'dzn': 15,
    'drm': 16,
    'gms': 17,
    'ggk': 18,
    'grs': 19,
    'gyd': 20,
    'kgs': 21,
    'klr': 22,
    'kme': 23,
    'ltr': 24,
    'mtr': 25,
    'mts': 26,
    'mlt': 27,
    'na': 28,
    'nos': 29,
    'oth': 30,
    'pac': 31,
    'prs': 32,
    'pcs': 33,
    'qtl': 34,
    'rol': 35,
    'set': 36,
    'sqf': 37,
    'sqm': 38,
    'sqy': 39,
    'tbs': 40,
    'tgm': 41,
    'thd': 42,
    'ton': 43,
    'tub': 44,
    'ugs': 45,
    'unt': 46,
    'yds': 47,
    'rft': 48
}

